-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 20:25:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema champion-challenges
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema champion-challenges
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `champion-challenges` DEFAULT CHARACTER SET utf8 ;
USE `champion-challenges` ;

-- -----------------------------------------------------
-- Table `champion-challenges`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `champion-challenges`.`user` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `champion-challenges`.`challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `champion-challenges`.`challenge` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `details` VARCHAR(255) NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `status` TINYINT NULL,
  `link` VARCHAR(255) NULL,
  `id_owner` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_challenge_user_idx` (`id_owner` ASC) VISIBLE,
  CONSTRAINT `fk_challenge_user`
    FOREIGN KEY (`id_owner`)
    REFERENCES `champion-challenges`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `champion-challenges`.`challenge_particpant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `champion-challenges`.`challenge_particpant` (
  `id_user` BINARY(16) NOT NULL,
  `id_challenge` BINARY(16) NOT NULL,
  `id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_challenge_participant_idx` (`id_challenge` ASC) VISIBLE,
  INDEX `fk_challenge_participant_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_challenge_participant`
    FOREIGN KEY (`id_challenge`)
    REFERENCES `champion-challenges`.`challenge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challenge_participant_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `champion-challenges`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `champion-challenges`.`invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `champion-challenges`.`invite` (
  `id_sender` BINARY(16) NOT NULL,
  `id_recipient` BINARY(16) NOT NULL,
  `id` BINARY(16) NOT NULL,
  `id_challenge` BINARY(16) NOT NULL,
  `status` TINYINT NULL,
  `sent_at` DATETIME NOT NULL,
  `responded_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sender_invite_idx` (`id_sender` ASC) VISIBLE,
  INDEX `fk_recipient_invite_idx` (`id_recipient` ASC) VISIBLE,
  INDEX `fk_challenge_invite_idx` (`id_challenge` ASC) VISIBLE,
  CONSTRAINT `fk_invite_sender`
    FOREIGN KEY (`id_sender`)
    REFERENCES `champion-challenges`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invite_recipient`
    FOREIGN KEY (`id_recipient`)
    REFERENCES `champion-challenges`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invite_challenge`
    FOREIGN KEY (`id_challenge`)
    REFERENCES `champion-challenges`.`challenge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
